### ISSUE TITLE
Latest Blog entries from RSS-Feed entries are Japanese

### ISSUE THREAD

**Issue by bynt** [canonical-web-and-design/blog.ubuntu.com#496]
## Summary
The last three entries of the Ubuntu blog RSS feed at
https://blog.ubuntu.com/feed
have been in Japanese
[ubuntu_feed.txt](https://github.com/canonical-websites/blog.ubuntu.com/files/2902638/ubuntu_feed.txt)

## Process
open
https://blog.ubuntu.com/feed

## Current and expected result
From experience I expected to get english articles only. If articles in multiple languages are thought to be delivered via RSS there should be an option to subscribe to a localized feed.

**Comment by caldav** [comment]
Thanks for reporting it, they should have been filtered out.

**Comment by caldav** [comment]
This issue is pretty visible here https://blog.ubuntu.com/feed?tag=developer, if you refresh it multiple times, you'll see Japanese content popping up in 2nd position from time to time. @nottrobin any idea? Looks like an issue in whatever is serving the feed, the latest code for the feed is definitely filtering the `lang:jp` tag: https://bazaar.launchpad.net/~canonical-website-editors/resource-centre/resource-centre/view/head:/functions/rss.php#L9

**Comment by nottrobin** [comment]
@caldav the same issue appears to be happening at https://admin.insights.ubuntu.com/feed?tag=developer (blog.ubuntu.com just proxies that URL). So it's an issue with the wordpress back-end, and therefore need an RT for IS to investigate.

**Comment by anthonydillon** [comment]
It sounds like the change didn't make it to all the front-ends. An RT is a good place to start. Mentioning the latest rev from the launchpad project.

**Comment by pmahnke** [comment]
I filed this bug over on the blog module - see https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/49

closing as a dup

**Comment by b-m-f** [comment]
Reopened. The blog module will get its own PR :)
